---
- hosts: web
  gather_facts: False

  vars:
    - root_dir: "{{ playbook_dir }}"
    - shared_dir: "{{ playbook_dir }}/../shared"


  vars_files:
    - ./le_vars.yml

  pre_tasks:
    - debug: msg="Pre tasks section"
      tags: always

    - name: ANSIBLE PYTHON | install python 2
      raw: test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)
      become: yes
      tags: always

    - name:  UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      apt: pkg="acl"
      become: yes
      tags: always

    - name: gather facts
      setup:
      tags: always

    - name: Include common pretasks
      include_tasks: "{{shared_dir}}/common_pretasks.yml"
      tags: always

  roles:
    - {
      role: "sa-acme-sh",
      le_config_properties: "{{ app_le_config_properties  }}",
      le_domains: "{{ app_le_domains }}",
      option_setup_cron: true,
      # Force certificates generation
      option_run_once:   true
      }

  tasks:

    - debug: msg="Pre tasks section"
