---
  - name: Create demo site folder
    file: path="/var/www/demo56" state="directory"
    become: yes

  - name: Push demo site contents
    synchronize: src="{{root_dir}}/files/demosite/" dest="/var/www/demo56"
    become: yes

  - name: Template demosite nginx config
    template: src="{{root_dir}}/templates/nginx/site56.conf.j2" dest="/etc/nginx/sites-enabled/site56.conf"
    dest: /var/www/demo56
    become: yes

  - name: Restart nginx
    service: name="nginx" state="restarted"
    become: yes
