---

  - block:

      - name: Postfix | Add postfix filter user
        user: name="postfixfilter" shell="/bin/false"
        become: yes
        tags:
          - postfix

      - name: Postfix | Create working directory
        file: path="/var/spool/filter" state="directory" owner="postfixfilter" group="postfixfilter"
        become: yes
        tags:
          - postfix

    when: option_postfix_content_filtering | default(false)

  - name: POSTFIX | Install mailutils
    apt: pkg=mailutils update_cache=yes
    become: yes
    tags:
     - postfix

  - name: POSTFIX | Install postfix
    apt: pkg=postfix update_cache=yes
    become: yes
    tags:
     - postfix


  - name: POSTFIX | Patch /etc/postfix/main.cf
    lineinfile: dest=/etc/postfix/main.cf  regexp="{{item.regexp}}" line="{{item.line}}" insertafter="{{item.insertafter | default('EOF')}}"
    with_items: "{{postfix_properties | default([])}}"
    notify: restart postfix
    become: yes
    tags:
     - postfix
