---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
# lint:
#   name: yamllint
platforms:
   - name: db01
     box: ubuntu/xenial64
     interfaces:
       - network_name: private_network
         type: dhcp
         auto_config: true
     groups:
       - db01
   - name: db02
     box: ubuntu/xenial64
     interfaces:
       - network_name: private_network
         type: dhcp
         auto_config: true
     groups:
       - db02
   - name: db03
     box: ubuntu/xenial64
     interfaces:
       - network_name: private_network
         type: dhcp
         auto_config: true
     groups:
       - db03

  # - name: trusty
  #   box: ubuntu/trusty64
  #   # interfaces:
  #   #   - network_name: public_network
  #   #     type: dhcp
  #   #     auto_config: true    
  # - name: xenial
  #   box: ubuntu/xenial64
  # - name: bionic
  #   box: ubuntu/bionic64
    # interfaces:
    #   - network_name: public_network
    #     type: dhcp
    #     auto_config: true
  # - name: centos6
  #   box: centos/6    
  # - name: centos7
  #   box: centos/7
  # - name: fedora28
  #   box: generic/fedora28
  # - name: alpine
  #   box: generic/alpine28

    
provisioner:
  name: ansible
  # lint:
  #   name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
