---
# https://github.com/Lusitaniae/apache_exporter
# https://github.com/Lusitaniae/apache_exporter/releases/download/v0.5.0/apache_exporter-0.5.0.linux-amd64.tar.gz
  - name: Set exporter facts
    set_fact:
      apache_exporter_sub_dir: "{{ exporter_config.exporter_dir | default('apache_exporter') }}"
      apache_exporter_user: "{{ exporter_config.exporter_user | default(prometheus_user) }}"
      apache_exporter_group: "{{ exporter_config.exporter_group | default(prometheus_group) }}"

  - name: Prometheus apache exporter | check if this exporter version exists
    stat:
      path: "{{ prometheus_exporters_dir }}/apache_exporter-{{ prometheus_apache_exporter_version }}.linux-amd64"
    register: apache_exporter_version_exists
    become: yes

  - name: Prometheus apache Exporter | Download distribution
    get_url:
      url: "https://github.com/Lusitaniae/apache_exporter/releases/download/v{{ prometheus_apache_exporter_version }}/apache_exporter-{{ prometheus_apache_exporter_version }}.linux-amd64.tar.gz"
      dest: "/tmp/apache_exporter-{{ prometheus_apache_exporter_version }}.linux-amd64.tar.gz"
    become: yes
    become_user: "{{ apache_exporter_user }}"
    when: not apache_exporter_version_exists.stat.exists
    tags:
      - prometheus

  - name: Prometheus apache Exporter | unpack distribution
    unarchive:
      src: "/tmp/apache_exporter-{{ prometheus_apache_exporter_version }}.linux-amd64.tar.gz"
      dest: "{{ prometheus_exporters_dir }}"
      remote_src: yes
    become: yes
    become_user: "{{ apache_exporter_user }}"
    when: not apache_exporter_version_exists.stat.exists
    tags:
      - prometheus

  - name: Prometheus apache Exporter | link apache exporter dir
    file:
      src: "{{ prometheus_exporters_dir }}/apache_exporter-{{ prometheus_apache_exporter_version }}.linux-amd64/"
      dest: "{{ prometheus_exporters_dir }}/{{ apache_exporter_sub_dir }}"
      owner: "root"
      group: "{{ apache_exporter_group }}"
      state: link
    become: yes
    tags:
      - prometheus

  - include_tasks: "tasks_startup.yml"
    vars:
      exporter_startup_config: "{{ exporter_config }}"