namespace: "softasap"
name: "monitored_box"
description: wraps sa-prometheus-exporters installs preselected exporters on a server
version: 0.3.0
readme: "Readme.md"
authors:
    - "Vyacheslav Voronenko"
dependencies:
license:
    - "MIT"
tags:
    - softasap
    - prometheus
    - exporters
repository: "https://github.com/oops-to-devops/monitored_box"
documentation: "https://github.com/oops-to-devops/monitored_box/blob/master/README.md"
homepage: "https://www.softasap.com"
issues: "https://github.com/orgs/oops-to-devops/projects/1"
